[RegularGrid]
n = 2
"Î³" = 5

["Î©"]
type="ReproducingKernel{:Cubic2D,:â–¡,:CubicSpline,:Tri3}"
"ğ“’".tag="Î©"
"ğ“’".type="TriRK13"
"ğ“–".type="TriRK13"
"ğ“–"."ğ­"="ğ­"

["Î©Ìƒ"]
type="ReproducingKernel{:Cubic2D,:â–¡,:CubicSpline,:Tri3}"
"ğ“’".tag="Î©"
"ğ“’".type="TriRK13"
"ğ“–".type="TriGI6"
"ğ“–"."ğ­"="âˆ‡Ìƒâ‚‚ğ­"

["Î“áµ—"]
type="ReproducingKernel{:Cubic2D,:â–¡,:CubicSpline,:Seg2}"
"ğ“’".tag="Î“áµ—"
"ğ“–".type="SegRK5"
"ğ“–".normal=true
"ğ“–"."ğ­"="ğ­"

["Î“áµ"]
type="ReproducingKernel{:Cubic2D,:â–¡,:CubicSpline,:Seg2}"
"ğ“’".tag="Î“áµ"
"ğ“–".type="SegRK5"
"ğ“–".normal=true
"ğ“–"."ğ­"="âˆ‡â‚‚ğ­"

